---
title: "`r params$title_text`"
output: pdf_document
geometry: margin=0.5in
fontsize: 10pt
params:
  title_text: NA
  test_type: NA
  question: NA
  results_table: NA
  plt: NA
  predict_table: NA
  interpretation: NA
  Most_likely: NA
  batch_results: NA
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(ggplot2)
```
## Question 
```{r results='asis'}
cat(params$question)
```

## Test Results

```{r}
knitr::kable(params$results_table)
```

## Predicted Probabilities Plot

```{r, fig.width=8, fig.height=6}
print(params$plt)
```

## Prediction Table

```{r}
knitr::kable(params$predict_table)
```

## Interpretations

```{r results='asis'}
cat(params$interpretation)
```


## Most Likely Responses per Wave 

```{r results='asis'}
cat(params$Most_likely)
```


## Batch Results 
```{r batch-results, echo=FALSE}
if (!is.null(params$batch_results) &&
    nrow(params$batch_results) > 0) {
  
  knitr::kable(
    params$batch_results,
    format = "latex",
    booktabs = TRUE,
    longtable = TRUE
  )
  
}
```


